[[module.imports]]
path = "github.com/hugomods/snackbar"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.encrypt]
password = ""
storage = "session"

[params.hugopress.modules.encrypt.hooks.head-end]

[params.hugopress.modules.encrypt.hooks.body-end]
